name: Musings by Jefff
markdown: redcarpet
highlighter: pygments
permalink: /:title
site_title: Musings by Jefff
site_desc: 'We love tech, and we love tunes. Here&rsquo;s a running list of tunes we&rsquo; diggin&rsquo;.'
site_file_name: 'b.jfff'
site_link: 'http://musings.jefff.co/'
site_full_link: 'http://hire.jefff.co/'